name: ci

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate Tag
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["tiwarisanjay/dex-example-app:latest","tiwarisanjay/dex-example-app:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["tiwarisanjay/dex-example-app:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS
      -
        name: Build and push
        uses: docker/build-push-action@v3
        needs: gen_tags
        with:
          context: .
          push: true
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}